coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/coverage/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.git/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

flags:
  unittests:
    paths:
      - src/
    carryforward: true

codecov:
  require_ci_to_pass: true
  bot: codecov-io
  max_report_age: 12h
  notify:
    after_n_builds: 3
    wait_for_ci: true 